import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html suppressHydrationWarning lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
          {/* <div className="grid h-svh grid-rows-[auto_1fr]">
            
          </div> */}
        </Providers>
      </body>
    </html>
  );
}
